WebApplication1/WebApplication1/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;



namespace WebApplication1.Controllers
{
    public class ClientesController : Controller
    {
        private WebBankingEntities17 db = new WebBankingEntities17();

        // GET: Clientes
        public ActionResult Index()
        {
            return View(db.Cliente.ToList());
        }

        // GET: Clientes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
           
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // GET: Clientes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idCliente,nombreCliente,usuario,identificacion,email,tipoUsuario,contrasena,estado")] Cliente cliente)
        {
            Cliente obj = new Cliente();
            obj.email = cliente.email;
           // cliente.EnviarCorreoElectronicos(obj.email);
            
            if (ModelState.IsValid)
            {
                db.Cliente.Add(cliente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idCliente,nombreCliente,usuario,identificacion,email,contrasena")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cliente);
        }


        public ActionResult InactivarCliente(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult InactivarCliente([Bind(Include = "idCliente,nombreCliente,usuario,identificacion,email,tipoUsuario,contrasena,estado")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                Cliente obj = new Cliente();
                if (cliente.tipoUsuario.Equals("Usuario")) { 
                    obj.nombreCliente = cliente.nombreCliente;
                    db.Entry(cliente).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cliente cliente = db.Cliente.Find(id);
            db.Cliente.Remove(cliente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
      //  public ActionResult ListadoClientes()
        //{


            //  ClienteModel modelo = new ClienteModel();
            //  modelo.cliente = new ConsultaCliente().ListadoClientes().ToList();
            //  modelo.Cuenta = modelo.CXC.idCuenta; ;
          /*  Cliente lisCliente = new Cliente();
            lisCliente.listaCliente = (from clie in db.Cliente
                                       join CXC in db.CuentaPorCliente
                                       on clie.idCliente equals CXC.idCliente
                                       join cuen in db.Cuenta
                                       on CXC.idCuenta equals cuen.idCuenta
                                       where (clie.estado.Equals("Activo"))

                                       select new Cliente{ nombreCliente = clie.nombreCliente, numCuenta = cuen.numCuenta, estado = clie.estado }).ToList();


            return View(lisCliente);*/
       // }
        [HttpPost]
        public ActionResult AddOrEdit(Cliente clienteModel)
        {
            using (WebBankingEntities17 bModel = new WebBankingEntities17()) 
            return View(clienteModel);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Descripción de la page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Su página de contacto.";

            return View();
        }
        public ActionResult Mantenimiento()
        {
            ViewBag.Message = "Aca podra selecionar la opcion a la que quiera dar mantenimiento";

            return View();
        }

        public ActionResult OpcCliente()
        {
            ViewBag.Message = "Opciones de Clientes";

            return View();
        }


    }
}

WebApplication1/WebApplication1/Controllers/TransferenciasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TransferenciasController : Controller
    {
        private WebBankingEntities17 db = new WebBankingEntities17();
        public CuentaPorCliente CXC = new CuentaPorCliente();

        public ActionResult Index()
        {
            var transferencia = db.Transferencia.Include(t => t.Cliente).Include(t => t.Cuenta);
            return View(transferencia.ToList());



        }

        // GET: Transferencias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transferencia transferencia = db.Transferencia.Find(id);
            if (transferencia == null)
            {
                return HttpNotFound();
            }
            return View(transferencia);
        }

        // GET: Transferencias/Create
        public ActionResult Create()
        {

            ViewBag.idcliente = new SelectList(db.Cliente, "idCliente", "nombreCliente");
            int i = (Int32)Session["idCliente"];


            var sql = from clie in db.Cliente
                      join CXC in db.CuentaPorCliente
                      on clie.idCliente equals CXC.idCliente
                      join cuen in db.Cuenta
                      on CXC.idCuenta equals cuen.idCuenta
                      where (clie.idCliente == (i))
                      select new
                      {
                          Numcuenta = cuen.numCuenta,
                          ciente = clie.idCliente,
                          idcuenta = cuen.idCuenta
                      };

            ViewBag.idcuentaOrigen = new SelectList(sql, "idCuenta", "numCuenta");
            return View();
        }

        // POST: Transferencias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.


        public void GetListadoClientesCuentas(Cliente clie)
        {
            try
            {
                IEnumerable<Cliente> values = Enum.GetValues(typeof(Cliente))
                    .Cast<Cliente>();

                IEnumerable<SelectListItem> items =
                    from value in values
                    select new SelectListItem
                    {
                        Text = value.ToString(),

                        Value = value.ToString(),

                        Selected = value == clie,
                    };
                ViewBag.Cuentas = items;


            }
            catch (Exception e)
            {
                Console.WriteLine(e.StackTrace);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string Nombre, [Bind(Include = "idTransferencia,idcliente,idcuentaOrigen,cuentaDestino,fechaHora,monto,detalle")] Transferencia transferencia)
        {
            Transferencia obj = new Transferencia();

            String format = "dd mm yyyy hh:mm tt";
            //var dat = new DateTime.Now;
            DateTime date = DateTime.Now;
            // Display the result string. 
            Console.WriteLine(date.ToString(format));
            int i = (Int32)Session["idCliente"];

            obj.idcliente = i;
            obj.idcuentaOrigen = transferencia.idcuentaOrigen;
            obj.cuentaDestino= transferencia.cuentaDestino;
            transferencia.fechaHora = date;
            obj.fechaHora = transferencia.fechaHora;
            obj.monto = transferencia.monto;
            obj.detalle = transferencia.detalle;

            int valor;
            int.TryParse(transferencia.cuentaDestino, out valor);
            //obj.ActualizarCuentas(i, transferencia.idcuentaOrigen, valor, transferencia.monto);

            if (ModelState.IsValid)
            {

                db.Transferencia.Add(obj);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            


            var sql = from clie in db.Cliente
                      join CXC in db.CuentaPorCliente
                      on clie.idCliente equals CXC.idCliente
                      join cuen in db.Cuenta
                      on CXC.idCuenta equals cuen.idCuenta
                      where (clie.idCliente == (i))
                      select new
                      {
                          Numcuenta = cuen.numCuenta,
                          ciente = clie.idCliente,
                          idcuenta = cuen.idCuenta
                      };
            string dir = Session["email"].ToString();
            obj.EnviarCorreoElectronicos(dir, transferencia.idcuentaOrigen.ToString(), transferencia.cuentaDestino, transferencia.monto, transferencia.detalle, 1);
            obj.EnviarCorreoElectronicos(dir, transferencia.idcuentaOrigen.ToString(), transferencia.cuentaDestino, transferencia.monto, transferencia.detalle, 2);                                

            ViewBag.idcuentaOrigen = new SelectList(sql, "idCuenta", "numCuenta");


            ViewBag.idcliente = new SelectList(db.Cliente, "idCliente", "nombreCliente", transferencia.idcliente);
            // ViewBag.idcuentaOrigen = new SelectList(db.Cuenta, "idCuenta", "numCuenta", transferencia.idcuentaOrigen);
            //ViewBag.idcuentaOrigen = ListadoClientesCuentas(transferencia.idcliente);
            // ViewBag.idcuentaOrigen = items;
           
            return View(transferencia);
        }

        

        // GET: Transferencias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transferencia transferencia = db.Transferencia.Find(id);
            if (transferencia == null)
            {
                return HttpNotFound();
            }
            ViewBag.idcliente = new SelectList(db.Cliente, "idCliente", "nombreCliente", transferencia.idcliente);
            ViewBag.idcuentaOrigen = new SelectList(db.Cuenta, "idCuenta", "numCuenta", transferencia.idcuentaOrigen);
            //  ViewBag.idcuentaOrigen = new SelectList(db.CuentaPorCliente.Where(c => c.idCliente == transferencia.idcliente), "idCliente", "numCuenta", transferencia.idcuentaOrigen);
            return View(transferencia);
        }

        // POST: Transferencias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idTransferencia,idcliente,idcuentaOrigen,cuentaDestino,fechaHora,monto,detalle")] Transferencia transferencia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(transferencia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idcliente = new SelectList(db.Cliente, "idCliente", "nombreCliente", transferencia.idcliente);
            ViewBag.idcuentaOrigen = new SelectList(db.Cuenta, "idCuenta", "numCuenta", transferencia.idcuentaOrigen);
            //   ViewBag.idcuentaOrigen = new SelectList(db.CuentaPorCliente.Where(c => c.idCliente == transferencia.idcliente), "idCliente", "numCuenta", transferencia.idcuentaOrigen);
            return View(transferencia);
        }

        // GET: Transferencias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transferencia transferencia = db.Transferencia.Find(id);
            if (transferencia == null)
            {
                return HttpNotFound();
            }
            return View(transferencia);
        }

        // POST: Transferencias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Transferencia transferencia = db.Transferencia.Find(id);
            db.Transferencia.Remove(transferencia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult listaServicios()
        {
            return View();
        }

        public ActionResult Nince(string identificador)
        {
            Servicio obj = new Servicio();


            return View();
        }
        
     /*  public ActionResult Validar(int identificador)
           
        {

        } */

        public ActionResult ObtenerTipoServicio(String tipo)
        {

            return  RedirectToAction("Nince", "Transferencias") ;
        }
        [HttpPost]
        public ActionResult PagoServicio(string TipoServicio)
        {

            ViewBag.idcliente = new SelectList(db.Cliente, "idCliente", "nombreCliente");
            int i = (Int32)Session["idCliente"];
            var numCuentaCliente = from clie in db.Cliente
                      join CXC in db.CuentaPorCliente
                      on clie.idCliente equals CXC.idCliente
                      join cuen in db.Cuenta
                      on CXC.idCuenta equals cuen.idCuenta
                      where (clie.idCliente == (i))
                      select new
                      {
                          Numcuenta = cuen.numCuenta,
                          ciente = clie.idCliente,
                          idcuenta = cuen.idCuenta
                      };

WebApplication1/WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "Acerca de...";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information. #YOLO!</p>

WebApplication1/WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contacto";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Inicio";
    if (Session["idCliente"] == null)
    {
        Response.Redirect("~/Login/Index");
    }

}

<html>
<head>
 
</head>
 <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">BVAM</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/Home">Inicio</a></li>
                        <li><a href="/Home/About">Acerca de</a></li>
                        <li><a href="/Home/Contact">Contacto</a></li>
                        <li> <a href="@Url.Action("LogOut", "Login")">Salir</a></li>
                        </ul>
                </div>
            </div>
        </div>
        <div>
            
            <h3> Bienvenido al sistema de web Banking: @Session["nombreCliente"].ToString()</h3>

                        
            <div>

                <div class="container">

                    @Html.ActionLink("Lista Servicios", "PagoServicio", "Transferencias")
                </div>

            </div>

            <div>

                <div class="container">

                    @Html.ActionLink("Transferencias", "Create", "Transferencias")
                </div>

            </div>


        </div>

    </body>
</html>

WebApplication1/WebApplication1/Views/Home/Mantenimiento.cshtml
@{
    Layout = null;
}

<style>
       .credit-card-div span { padding-top:10px; }
     .credit-card-div img { padding-top:30px; }
     .credit-card-div .small-font { font-size:9px; }
     .credit-card-div .pad-adjust { padding-top:10px; }

</style>

<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio - Mi aplicación ASP.NET</title>
    <link href="/Content/bootstrap.css" rel="stylesheet" />
    <link href="/Content/site.css" rel="stylesheet" />

    <script src="/Scripts/modernizr-2.8.3.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Nombre de aplicaci&#243;n</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Inicio</a></li>
                    <li><a href="/Home/About">Acerca de</a></li>
                    <li><a href="/Home/Contact">Contacto</a></li>
                    <li><a href="/Home/Mantenimiento">Mantenimiento</a></li>

                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        <h1>Opciones Mantenimiento Clientes</h1>

        <label> Seleccione la opcion a la que le desea dar mantenimiento </label>
        <div class="container">

            <a href="/Home/OpcCliente">Clientes</a>
        </div>

        <div clas>

            @Html.ActionLink("Servicios", "Index", "Servicios")
        </div>
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</body>

</html>

WebApplication1/WebApplication1/Views/Home/OpcCliente.cshtml
<!DOCTYPE html>

<html>

<body>

    <div>

        <table class="table">
            <tr>
                <th>
                    <div>
                    <p>
                        Agregar Cliente
                        @Html.ActionLink("Create", "Index", "Clientes")
                    </p>
                </div>
                </th>
                <th>
                    <div>
                        <p>
                            Inactivar Cliente
                            @Html.ActionLink("InactivarCliente", "Index", "Clientes")
                        </p>
                    </div>
                </th>
                <th> 
                    <div>
                        <p>
                            Actualizar Cliente
                            @Html.ActionLink("Edit", "Index", "Clientes")
                        </p>
                    </div>
                </th>
            </tr>

        </table>
    </div>
     
</body>
</html>

WebApplication1/WebApplication1/Views/Home/OpcServicio.cshtml
@{
    ViewBag.Title = "OpcServicio";
}

<html>

<body>

    <div>

        <table class="table">
            <tr>
                <th>
                    <div>
                        <p>
                            Agregar Servicio
                            @Html.ActionLink("Create", "Index", "Servicios")
                        </p>
                    </div>
                </th>
                <th>
                    <div>
                        <p>
                            Consultar Informacion Servicio
                            @Html.ActionLink("Details", "Index", "Servicios")
                        </p>
                    </div>
                </th>
                <th>
                    <div>
                        <p>
                            Actualizar Servicio
                            @Html.ActionLink("Edit", "Index", "Servicios")
                        </p>
                    </div>
                </th>

                <th>
                    <div>
                        <p>
                            Inactivar Servicio
                            @Html.ActionLink("CambiarEstado", "Index", "Servicios")
                        </p>
                    </div>
                </th>
            </tr>

        </table>
    </div>

</body>
</html>

WebApplication1/WebApplication1/Views/Home/RealizarTransferencias.cshtml
@{
    ViewBag.Title = "Transferencias";
}

<h2>Transaferencias</h2>

<!DOCTYPE html>

<html>

<body>

    <div>

        <table class="table">
            <tr>
                <th>
                    <div>
                        <p>
                           Transferencias
                            @Html.ActionLink("Create", "Index", "Transferencias")
                        </p>
                    </div>
                </th>
                <th>
                    <div>
                        <p>
                            Pagos
                            @Html.ActionLink("PagoServicio", "Index", "Servicios")
                        </p>
                    </div>
                </th>
               
            </tr>

        </table>
    </div>

</body>
</html>

WebApplication1/WebApplication1/Views/Home/Transferencias.cshtml
@{
    ViewBag.Title = "Transaferencias";
}

<h2>Transaferencias</h2>

<!DOCTYPE html>

<html>

<body>

    <div>

        <table class="table">
            <tr>
                <th>
                    <div>
                        <p>
                           Transferencias
                            @Html.ActionLink("Create", "Index", "Transferencias")
                        </p>
                    </div>
                </th>
                <th>
                    <div>
                        <p>
                            Pagos
                            
                        </p>
                    </div>
                </th>
               
            </tr>

        </table>
    </div>

</body>
</html>